INSERT INTO Player(playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES('NZL01', 1, 31, 'GK', 'Erin', 'Nayler', 'New Zealander', 'NZL'),
('NZL02', 2, 33, 'MF', 'Ria', 'Percival', 'New Zealander', 'NZL'),
('NZL03', 3, 23, 'DF', 'Claudia', 'Bunge', 'New Zealander', 'NZL'),
('NZL04', 4, 28, 'DF', 'CJ', 'Bott', 'New Zealander', 'NZL'),
('NZL05', 5, 24, 'DF', 'Michaela', 'Foster', 'New Zealander', 'NZL'),
('NZL06', 6, 24, 'MF', 'Malia', 'Steinmetz', 'New Zealander', 'NZL'),
('NZL07', 7, 35, 'DF', 'Ali', 'Riley', 'New Zealander', 'NZL'),
('NZL08', 8, 26, 'MF', 'Daisy', 'Cleverley', 'New Zealander', 'NZL'),
('NZL09', 9, 22, 'FW', 'Gabi', 'Rennie', 'New Zealander', 'NZL'),
('NZL10', 10, 32, 'MF', 'Annalie', 'Longo', 'New Zealander', 'NZL'),
('NZL11', 11, 29, 'MF', 'Olivia', 'Chance', 'New Zealander', 'NZL'),
('NZL12', 12, 32, 'MF', 'Betsy', 'Hassett', 'New Zealander', 'NZL'),
('NZL13', 13, 30, 'DF', 'Rebekah', 'Stott', 'New Zealander', 'NZL'),
('NZL14', 14, 29, 'DF', 'Katie', 'Bowen', 'New Zealander', 'NZL'),
('NZL15', 15, 25, 'FW', 'Paige', 'Satchell', 'New Zealander', 'NZL'),
('NZL16', 16, 24, 'FW', 'Jacqui', 'Hand', 'New Zealander', 'NZL'),
('NZL17', 17, 31, 'FW', 'Hannah', 'Wilkinson', 'New Zealander', 'NZL'),
('NZL18', 18, 24, 'FW', 'Grace', 'Jale', 'New Zealander', 'NZL'),
('NZL19', 19, 24, 'DF', 'Elizabeth', 'Anton', 'New Zealander', 'NZL'),
('NZL20', 20, 21, 'FW', 'Indiah-Paige', 'Riley', 'New Zealander', 'NZL'),
('NZL21', 21, 32, 'GK', 'Victoria', 'Esson', 'New Zealander', 'NZL'),
('NZL22', 22, 17, 'FW', 'Milly', 'Clegg', 'New Zealander', 'NZL'),
('NZL23', 23, 22, 'GK', 'Anna', 'Leat', 'New Zealander', 'NZL');

INSERT INTO Player(playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('NOR01', 1, 27, 'GK', 'Cecilie', 'Fiskerstrand', 'Norwegian', 'NOR'),
    ('NOR02', 2, 31, 'DF', 'Anja', 'Sonstevold', 'Norwegian', 'NOR'),
    ('NOR03', 3, 22, 'DF', 'Sara', 'Horte', 'Norwegian', 'NOR'),
    ('NOR04', 4, 25, 'DF', 'Tuva', 'Hansen', 'Norwegian', 'NOR'),
    ('NOR05', 5, 29, 'DF', 'Guro', 'Bergsvand', 'Norwegian', 'NOR'),
    ('NOR06', 6, 33, 'DF', 'Maren', 'Mjelde', 'Norwegian', 'NOR'),
    ('NOR07', 7, 25, 'MF', 'Ingrid', 'Syrstad', 'Norwegian', 'NOR'),
    ('NOR08', 8, 28, 'MF', 'Vilde Boe', 'Risa', 'Norwegian', 'NOR'),
    ('NOR09', 9, 27, 'FW', 'Karina', 'Saevik', 'Norwegian', 'NOR'),
    ('NOR10', 10, 28, 'MF', 'Caroline Graham', 'Hansen', 'Norwegian', 'NOR'),
    ('NOR11', 11, 28, 'MF', 'Guro', 'Reiten', 'Norwegian', 'NOR'),
    ('NOR12', 12, 31, 'GK', 'Guro', 'Pettersen', 'Norwegian', 'NOR'),
    ('NOR13', 13, 23, 'MF', 'Thea', 'Bjelde', 'Norwegian', 'NOR'),
    ('NOR14', 14, 28, 'FW', 'Ada', 'Hegerberg', 'Norwegian', 'NOR'),
    ('NOR15', 15, 27, 'MF', 'Amalie', 'Eikeland', 'Norwegian', 'NOR'),
    ('NOR16', 16, 21, 'DF', 'Mathilde', 'Harviken', 'Norwegian', 'NOR'),
    ('NOR17', 17, 21, 'FW', 'Julie', 'Blakstad', 'Norwegian', 'NOR'),
    ('NOR18', 18, 24, 'MF', 'Frida', 'Maanum', 'Norwegian', 'NOR'),
    ('NOR19', 19, 25, 'DF', 'Marit Bratberg', 'Lund', 'Norwegian', 'NOR'),
    ('NOR20', 20, 31, 'MF', 'Emilie', 'Haavi', 'Norwegian', 'NOR'),
    ('NOR21', 21, 22, 'FW', 'Anna', 'Josendal', 'Norwegian', 'NOR'),
    ('NOR22', 22, 24, 'FW', 'Sophie Roman', 'Haug', 'Norwegian', 'NOR'),
    ('NOR23', 23, 27, 'GK', 'Aurora', 'Mikalsen', 'Norwegian', 'NOR');

INSERT INTO Player(playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('PHI01', 1, 25, 'GK', 'Olivia', 'McDaniel', 'Filipnos', 'PHI'),
    ('PHI02', 2, 19, 'DF', 'Malea', 'Cesar', 'Filipnos', 'PHI'),
    ('PHI03', 3, 23, 'DF', 'Jessika', 'Cowart', 'Filipnos', 'PHI'),
    ('PHI04', 4, 30, 'MF', 'Jaclyn', 'Sawicki', 'Filipnos', 'PHI'),
    ('PHI05', 5, 28, 'DF', 'Hali', 'Long', 'Filipnos', 'PHI'),
    ('PHI06', 6, 34, 'MF', 'Tahnai', 'Annis', 'Filipnos', 'PHI'),
    ('PHI07', 7, 27, 'FW', 'Sarina', 'Bolden', 'Filipnos', 'PHI'),
    ('PHI08', 8, 26, 'MF', 'Sara', 'Eggesvik', 'Filipnos', 'PHI'),
    ('PHI09', 9, 18, 'FW', 'Isabella', 'Flanigan', 'Filipnos', 'PHI'),
    ('PHI10', 10, 25, 'FW', 'Chandler', 'McDaniel', 'Filipnos', 'PHI'),
    ('PHI11', 11, 23, 'MF', 'Anicka', 'Castaneda', 'Filipnos', 'PHI'),
    ('PHI12', 12, 27, 'MF', 'Ryley', 'Bugay', 'Filipnos', 'PHI'),
    ('PHI13', 13, 25, 'DF', 'Angela', 'Beard', 'Filipnos', 'PHI'),
    ('PHI14', 14, 26, 'FW', 'Meryll', 'Serrano', 'Filipnos', 'PHI'),
    ('PHI15', 15, 21, 'FW', 'Carleigh', 'Frilles', 'Filipnos', 'PHI'),
    ('PHI16', 16, 24, 'DF', 'Sofia', 'Harrison', 'Filipnos', 'PHI'),
    ('PHI17', 17, 25, 'DF', 'Alicia', 'Barker', 'Filipnos', 'PHI'),
    ('PHI18', 18, 17, 'GK', 'Kaiya', 'Jota', 'Filipnos', 'PHI'),
    ('PHI19', 19, 28, 'DF', 'Dominique', 'Randle', 'Filipnos', 'PHI'),
    ('PHI20', 20, 26, 'MF', 'Quinley', 'Quezada', 'Filipnos', 'PHI'),
    ('PHI21', 21, 29, 'FW', 'Katrina', 'Guillou', 'Filipnos', 'PHI'),
    ('PHI22', 22, 23, 'GK', 'Kiara', 'Fontanilla', 'Filipnos', 'PHI'),
    ('PHI23', 23, 24, 'DF', 'Reina', 'Bonta', 'Filipnos', 'PHI');

INSERT INTO Player(playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('SWI01', 1, 37, 'GK', 'Gaelle', 'Thalmann', 'Swiss', 'SWI'),
    ('SWI02', 2, 26, 'DF', 'Julia', 'Stierli', 'Swiss', 'SWI'),
    ('SWI03', 3, 23, 'DF', 'Lara', 'Marti', 'Swiss', 'SWI'),
    ('SWI04', 4, 21, 'DF', 'Laura', 'Felber', 'Swiss', 'SWI'),
    ('SWI05', 5, 27, 'DF', 'Noelle', 'Maritz', 'Swiss', 'SWI'),
    ('SWI06', 6, 24, 'MF', 'Geraldine', 'Reuteler', 'Swiss', 'SWI'),
    ('SWI07', 7, 23, 'FW', 'Amira', 'Arfaoui', 'Swiss', 'SWI'),
    ('SWI08', 8, 23, 'DF', 'Nadine', 'Riesen', 'Swiss', 'SWI'),
    ('SWI09', 9, 32, 'FW', 'Ana Maria', 'Crnogoreevic', 'Swiss', 'SWI'),
    ('SWI10', 10, 32, 'FW', 'Ramona', 'Bachmann', 'Swiss', 'SWI'),
    ('SWI11', 11, 28, 'MF', 'Coumba', 'Sow', 'Swiss', 'SWI'),
    ('SWI12', 12, 21, 'GK', 'Livia', 'Peng', 'Swiss', 'SWI'),
    ('SWI13', 13, 30, 'MF', 'Lia', 'Walti', 'Swiss', 'SWI'),
    ('SWI14', 14, 24, 'MF', 'Marion', 'Rey', 'Swiss', 'SWI'),
    ('SWI15', 15, 27, 'DF', 'Luana', 'Buhler', 'Swiss', 'SWI'),
    ('SWI16', 16, 26, 'MF', 'Sandrine', 'Mauron', 'Swiss', 'SWI'),
    ('SWI17', 17, 23, 'MF', 'Seraina', 'Piubel', 'Swiss', 'SWI'),
    ('SWI18', 18, 27, 'DF', 'Viola', 'Calligaris', 'Swiss', 'SWI'),
    ('SWI19', 19, 30, 'DF', 'Eseosa', 'Aigbogun', 'Swiss', 'SWI'),
    ('SWI20', 20, 36, 'FW', 'Fabienne', 'Humm', 'Swiss', 'SWI'),
    ('SWI21', 21, 30, 'GK', 'Seraina', 'Friedli', 'Swiss', 'SWI'),
    ('SWI22', 22, 27, 'FW', 'Meriame', 'Terchoun', 'Swiss', 'SWI'),
    ('SWI23', 23, 24, 'FW', 'Alisha', 'Lehmann', 'Swiss', 'SWI');

INSERT INTO Player(playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('AUS01', 1, 35, 'GK', 'Lydia', 'Williams', 'Australian', 'AUS'),
    ('AUS02', 2, 21, 'DF', 'Courtney', 'Nevin', 'Australian', 'AUS'),
    ('AUS03', 3, 38, 'DF', 'Aivi', 'Luik', 'Australian', 'AUS'),
    ('AUS04', 4, 34, 'DF', 'Clare', 'Polkinghorne', 'Australian', 'AUS'),
    ('AUS05', 5, 25, 'FW', 'Cortnee', 'Vine', 'Australian', 'AUS'),
    ('AUS06', 6, 25, 'MF', 'Clare', 'Wheeler', 'Australian', 'AUS'),
    ('AUS07', 7, 29, 'DF', 'Steph', 'Catley', 'Australian', 'AUS'),
    ('AUS08', 8, 24, 'MF', 'Alex', 'Chidiac', 'Australian', 'AUS'),
    ('AUS09', 9, 28, 'FW', 'Caitlin', 'Foord', 'Australian', 'AUS'),
    ('AUS10', 10, 30, 'MF', 'Emily', 'van Egmond', 'Australian', 'AUS'),
    ('AUS11', 11, 20, 'FW', 'Mary', 'Fowler', 'Australian', 'AUS'),
    ('AUS12', 12, 25, 'GK', 'Teagan', 'Micah', 'Australian', 'AUS'),
    ('AUS13', 13, 32, 'MF', 'Tameka', 'Yallop', 'Australian', 'AUS'),
    ('AUS14', 14, 28, 'DF', 'Alanna', 'Kennedy', 'Australian', 'AUS'),
    ('AUS15', 15, 24, 'DF', 'Clare', 'Hunt', 'Australian', 'AUS'),
    ('AUS16', 16, 28, 'FW', 'Hayley', 'Raso', 'Australian', 'AUS'),
    ('AUS17', 17, 32, 'FW', 'Kyah', 'Simon', 'Australian', 'AUS'),
    ('AUS18', 18, 29, 'GK', 'Mackenzie', 'Arnold', 'Australian', 'AUS'),
    ('AUS19', 19, 30, 'MF', 'Katrina', 'Gorry', 'Australian', 'AUS'),
    ('AUS20', 20, 29, 'FW', 'Sam', 'Kerr', 'Australian', 'AUS'),
    ('AUS21', 21, 23, 'DF', 'Ellie', 'Carpenter', 'Australian', 'AUS'),
    ('AUS22', 22, 21, 'DF', 'Charlotte', 'Grant', 'Australian', 'AUS'),
    ('AUS23', 23, 21, 'MF', 'Kyra', 'Cooney-Cross', 'Australian', 'AUS');

INSERT INTO Player(playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('CAN01', 1, 28, 'GK', 'Kailen', 'Sheridan', 'Canadian', 'CAN'),
    ('CAN02', 2, 34, 'DF', 'Allysha', 'Chapman', 'Canadian', 'CAN'),
    ('CAN03', 3, 27, 'DF', 'Kadeisha', 'Buchanan', 'Canadian', 'CAN'),
    ('CAN04', 4, 30, 'DF', 'Shelina', 'Zadorsky', 'Canadian', 'CAN'),
    ('CAN05', 5, 27, 'MF', 'Quinn', 'Rebecca', 'Canadian', 'CAN'),
    ('CAN06', 6, 24, 'FW', 'Deanne', 'Rose', 'Canadian', 'CAN'),
    ('CAN07', 7, 22, 'MF', 'Julia', 'Grosso', 'Canadian', 'CAN'),
    ('CAN08', 8, 22, 'DF', 'Jayde', 'Riviere', 'Canadian', 'CAN'),
    ('CAN09', 9, 22, 'FW', 'Jordyn', 'Huitema', 'Canadian', 'CAN'),
    ('CAN10', 10, 28, 'DF', 'Ashley', 'Lawrence', 'Canadian', 'CAN'),
    ('CAN11', 11, 26, 'FW', 'Evelyne', 'Viens', 'Canadian', 'CAN'),
    ('CAN12', 12, 40, 'FW', 'Christine', 'Sinclair', 'Canadian', 'CAN'),
    ('CAN13', 13, 35, 'MF', 'Sophie', 'Schmidt', 'Canadian', 'CAN'),
    ('CAN14', 14, 27, 'DF', 'Vanessa', 'Gilles', 'Canadian', 'CAN'),
    ('CAN15', 15, 28, 'FW', 'Nichelle', 'Prince', 'Canadian', 'CAN'),
    ('CAN16', 16, 24, 'DF', 'Gabrielle', 'Carle', 'Canadian', 'CAN'),
    ('CAN17', 17, 25, 'MF', 'Jessie', 'Fleming', 'Canadian', 'CAN'),
    ('CAN18', 18, 30, 'GK', 'Sabrina', 'DAngelo', 'Canadian', 'CAN'),
    ('CAN19', 19, 30, 'FW', 'Adriana', 'Leon', 'Canadian', 'CAN'),
    ('CAN20', 20, 30, 'FW', 'Cloe', 'Lacasse', 'Canadian', 'CAN'),
    ('CAN21', 21, 19, 'MF', 'Simi', 'Awujo', 'Canadian', 'CAN'),
    ('CAN22', 22, 24, 'GK', 'Lysianne', 'Proulx', 'Canadian', 'CAN'),
    ('CAN23', 23, 18, 'MF', 'Olivia', 'Smith', 'Canadian', 'CAN');

INSERT INTO Player(playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('NGA01', 1, 36, 'GK', 'Tochukwu', 'Oluehi', 'Nigerian', 'NGA'),
    ('NGA02', 2, 25, 'DF', 'Ashleigh', 'Plumptre', 'English', 'NGA'),
    ('NGA03', 3, 31, 'DF', 'Osinachi', 'Ohale', 'Nigerian', 'NGA'),
    ('NGA04', 4, 24, 'DF', 'Glory', 'Ogbonna', 'Nigerian', 'NGA'),
    ('NGA05', 5, 40, 'DF', 'Onome', 'Ebi', 'Nigerian', 'NGA'),
    ('NGA06', 6, 29, 'FW', 'Ifeoma', 'Onumonu', 'Nigerian', 'NGA'),
    ('NGA07', 7, 28, 'MF', 'Toni', 'Payne', 'Nigerian', 'NGA'),
    ('NGA08', 8, 28, 'FW', 'Asisat', 'Oshoala', 'Nigerian', 'NGA'),
    ('NGA09', 9, 29, 'FW', 'Desire', 'Oparanozie', 'Nigerian', 'NGA'),
    ('NGA10', 10, 22, 'MF', 'Christy', 'Ucheibe', 'Nigerian', 'NGA'),
    ('NGA11', 11, 21, 'FW', 'Gift', 'Monday', 'Nigerian', 'NGA'),
    ('NGA12', 12, 26, 'FW', 'Uchenna', 'Kanu', 'Nigerian', 'NGA'),
    ('NGA13', 13, 19, 'MF', 'Deborah', 'Abiodun', 'Nigerian', 'NGA'),
    ('NGA14', 14, 21, 'DF', 'Oluwatosin', 'Demehin', 'Nigerian', 'NGA'),
    ('NGA15', 15, 23, 'MF', 'Rasheedat', 'Ajibade', 'Nigerian', 'NGA'),
    ('NGA16', 16, 22, 'GK', 'Chiamaka', 'Nnadozie', 'Nigerian', 'NGA'),
    ('NGA17', 17, 29, 'FW', 'Francisca', 'Ordega', 'Nigerian', 'NGA'),
    ('NGA18', 18, 28, 'MF', 'Halimatu', 'Ayinde', 'Nigerian', 'NGA'),
    ('NGA19', 19, 22, 'MF', 'Jennifer', 'Echegini', 'Nigerian', 'NGA'),
    ('NGA20', 20, 19, 'DF', 'Rofiat', 'Imuran', 'Nigerian', 'NGA'),
    ('NGA21', 21, 26, 'FW', 'Esther', 'Okoronkwo', 'Nigerian', 'NGA'),
    ('NGA22', 22, 26, 'DF', 'Michelle', 'Alozie', 'Nigerian', 'NGA'),
    ('NGA23', 23, 33, 'GK', 'Yewande', 'Balogun', 'Nigerian', 'NGA');

INSERT INTO Player(playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('IRE01', 1, 27, 'GK', 'Courtney', 'Brosnan', 'Irish', 'IRE'),
    ('IRE02', 2, 28, 'DF', 'Claire', 'O''Riordan', 'Irish', 'IRE'),
    ('IRE03', 3, 27, 'DF', 'Chloe', 'Mustaki', 'Irish', 'IRE'),
    ('IRE04', 4, 33, 'DF', 'Louise', 'Quinn', 'Irish', 'IRE'),
    ('IRE05', 5, 35, 'DF', 'Niamh', 'Fahey', 'Irish', 'IRE'),
    ('IRE06', 6, 26, 'MF', 'Megan', 'Connolly', 'Irish', 'IRE'),
    ('IRE07', 7, 34, 'DF', 'Diane', 'Caldwell', 'Irish', 'IRE'),
    ('IRE08', 8, 33, 'MF', 'Ruesha', 'Littlejohn', 'Irish', 'IRE'),
    ('IRE09', 9, 27, 'FW', 'Amber', 'Barrett', 'Irish', 'IRE'),
    ('IRE10', 10, 29, 'MF', 'Denise', 'O''Sullivan', 'Irish', 'IRE'),
    ('IRE11', 11, 27, 'MF', 'Katie', 'McCabe', 'Irish', 'IRE'),
    ('IRE12', 12, 29, 'MF', 'Lily', 'Agg', 'Irish', 'IRE'),
    ('IRE13', 13, 34, 'DF', 'Aine', 'O''Gorman', 'Irish', 'IRE'),
    ('IRE14', 14, 23, 'DF', 'Heather', 'Payne', 'Irish', 'IRE'),
    ('IRE15', 15, 29, 'MF', 'Lucy', 'Quinn', 'Irish', 'IRE'),
    ('IRE16', 16, 30, 'GK', 'Grace', 'Moloney', 'Irish', 'IRE'),
    ('IRE17', 17, 33, 'MF', 'Sinead', 'Farrelly', 'Irish', 'IRE'),
    ('IRE18', 18, 27, 'FW', 'Kyra', 'Carusa', 'Irish', 'IRE'),
    ('IRE19', 19, 18, 'FW', 'Abbie', 'Larkin', 'Irish', 'IRE'),
    ('IRE20', 20, 26, 'FW', 'Marissa', 'Sheva', 'Irish', 'IRE'),
    ('IRE21', 21, 30, 'MF', 'Ciara', 'Grant', 'Irish', 'IRE'),
    ('IRE22', 22, 22, 'DF', 'Isibeal', 'Atkinson', 'Irish', 'IRE'),
    ('IRE23', 23, 28, 'GK', 'Megan', 'Walsh', 'Irish', 'IRE');

INSERT INTO Player(playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('COS01', 1, 18, 'GK', 'Genesis', 'Perez', 'Costa Rican', 'COS'),
    ('COS02', 2, 31, 'DF', 'Gabriela', 'Guillen', 'Costa Rican', 'COS'),
    ('COS03', 3, 25, 'DF', 'Maria', 'Coto', 'Costa Rican', 'COS'),
    ('COS04', 4, 28, 'DF', 'Mariana', 'Benavides', 'Costa Rican', 'COS'),
    ('COS05', 5, 23, 'DF', 'Valeria', 'del Campo', 'Costa Rican', 'COS'),
    ('COS06', 6, 37, 'DF', 'Carol', 'Sanchez', 'Colombian', 'COS'),
    ('COS07', 7, 26, 'MF', 'Melissa', 'Herrera', 'Costa Rican', 'COS'),
    ('COS08', 8, 24, 'MF', 'Mariela', 'Campos', 'Costa Rican', 'COS'),
    ('COS09', 9, 21, 'FW', 'Maria Paula', 'Salas', 'Costa Rican', 'COS'),
    ('COS10', 10, 23, 'MF', 'Gloriana', 'Villalobos', 'Costa Rican', 'COS'),
    ('COS11', 11, 29, 'MF', 'Raquel', 'Rodriguez', 'Costa Rican', 'COS'),
    ('COS12', 12, 24, 'DF', 'Maria Paula', 'Elizondo', 'Costa Rican', 'COS'),
    ('COS13', 13, 26, 'MF', 'Emilie', 'Valenciano', 'Costa Rican', 'COS'),
    ('COS14', 14, 22, 'MF', 'Priscila', 'Chinchilla', 'Costa Rican', 'COS'),
    ('COS15', 15, 33, 'MF', 'Cristin', 'Granados', 'Costa Rican', 'COS'),
    ('COS16', 16, 32, 'MF', 'Katherine', 'Alvarado', 'Costa Rican', 'COS'),
    ('COS17', 17, 25, 'FW', 'Sofia', 'Varela', 'Costa Rican', 'COS'),
    ('COS18', 18, 32, 'GK', 'Priscilla', 'Tapia', 'Costa Rican', 'COS'),
    ('COS19', 19, 20, 'MF', 'Alexandra', 'Pinell', 'Costa Rican', 'COS'),
    ('COS20', 20, 25, 'DF', 'Fabiola', 'Villalobos', 'Costa Rican', 'COS'),
    ('COS21', 21, 16, 'MF', 'Sheika', 'Scott', 'Costa Rican', 'COS'),
    ('COS22', 22, 24, 'FW', 'Catalina', 'Estrada', 'Costa Rican', 'COS'),
    ('COS23', 23, 25, 'GK', 'Daniela', 'Solera', 'Costa Rican', 'COS');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('JPN01', 1, 27, 'GK', 'Ayaka', 'Yamashita', 'Japanese', 'JPN'),
    ('JPN02', 2, 27, 'DF', 'Risa', 'Shimizu', 'Japanese', 'JPN'),
    ('JPN03', 3, 24, 'DF', 'Moeka', 'Minami', 'Japanese', 'JPN'),
    ('JPN04', 4, 32, 'DF', 'Saki', 'Kumagai', 'Japanese', 'JPN'),
    ('JPN05', 5, 27, 'DF', 'Shiori', 'Miyake', 'Japanese', 'JPN'),
    ('JPN06', 6, 26, 'MF', 'Hina', 'Sugita', 'Japanese', 'JPN'),
    ('JPN07', 7, 23, 'MF', 'Hinata', 'Miyazawa', 'Japanese', 'JPN'),
    ('JPN08', 8, 29, 'MF', 'Hikaru', 'Naomoto', 'Japanese', 'JPN'),
    ('JPN09', 9, 23, 'FW', 'Riko', 'Ueki', 'Japanese', 'JPN'),
    ('JPN10', 10, 24, 'MF', 'Fuka', 'Nagano', 'Japanese', 'JPN'),
    ('JPN11', 11, 29, 'FW', 'Mina', 'Tanaka', 'Japanese', 'JPN'),
    ('JPN12', 12, 23, 'DF', 'Hana', 'Takahashi', 'Japanese', 'JPN'),
    ('JPN13', 13, 23, 'MF', 'Jun', 'Endo', 'Japanese', 'JPN'),
    ('JPN14', 14, 26, 'MF', 'Yui', 'Hasegawa', 'Japanese', 'JPN'),
    ('JPN15', 15, 19, 'MF', 'Aoba', 'Fujino', 'Japanese', 'JPN'),
    ('JPN16', 16, 25, 'MF', 'Honoka', 'Hayashi', 'Japanese', 'JPN'),
    ('JPN17', 17, 26, 'DF', 'Kiko', 'Seike', 'Japanese', 'JPN'),
    ('JPN18', 18, 23, 'GK', 'Momoko', 'Tanaka', 'Japanese', 'JPN'),
    ('JPN19', 19, 26, 'DF', 'Miyabi', 'Moroya', 'Japanese', 'JPN'),
    ('JPN20', 20, 19, 'FW', 'Maika', 'Hamano', 'Japanese', 'JPN'),
    ('JPN21', 21, 26, 'GK', 'Chika', 'Hirao', 'Japanese', 'JPN'),
    ('JPN22', 22, 24, 'FW', 'Remina', 'Chiba', 'Japanese', 'JPN'),
    ('JPN23', 23, 20, 'DF', 'Rion', 'Ishikawa', 'Japanese', 'JPN');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('ESP01', 1, 23, 'GK', 'Misa', 'Rodriguez', 'Spanish', 'ESP'),
    ('ESP02', 2, 24, 'DF', 'Ona', 'Batlle', 'Spanish', 'ESP'),
    ('ESP03', 3, 23, 'MF', 'Teresa', 'Abelleira', 'Spanish', 'ESP'),
    ('ESP04', 4, 32, 'DF', 'Irene', 'Paredes', 'Spanish', 'ESP'),
    ('ESP05', 5, 29, 'DF', 'Ivana', 'Andres', 'Spanish', 'ESP'),
    ('ESP06', 6, 25, 'MF', 'Aitana', 'Bonmati', 'Spanish', 'ESP'),
    ('ESP07', 7, 26, 'MF', 'Irene', 'Guerrero', 'Spanish', 'ESP'),
    ('ESP08', 8, 27, 'FW', 'Mariona', 'Caldentey', 'Spanish', 'ESP'),
    ('ESP09', 9, 30, 'FW', 'Esther', 'Gonzalez', 'Spanish', 'ESP'),
    ('ESP10', 10, 33, 'MF', 'Jennifer', 'Hermoso', 'Spanish', 'ESP'),
    ('ESP11', 11, 29, 'MF', 'Alexia', 'Putellas', 'Spanish', 'ESP'),
    ('ESP12', 12, 23, 'DF', 'Oihane', 'Hernandez', 'Spanish', 'ESP'),
    ('ESP13', 13, 21, 'GK', 'Enith', 'Salon', 'Spanish', 'ESP'),
    ('ESP14', 14, 23, 'DF', 'Laia', 'Codina', 'Spanish', 'ESP'),
    ('ESP15', 15, 22, 'FW', 'Eva', 'Navarro', 'Spanish', 'ESP'),
    ('ESP16', 16, 21, 'MF', 'Maria', 'Perez', 'Spanish', 'ESP'),
    ('ESP17', 17, 26, 'FW', 'Alba', 'Redondo', 'Spanish', 'ESP'),
    ('ESP18', 18, 19, 'FW', 'Salma', 'Paralluelo', 'Spanish', 'ESP'),
    ('ESP19', 19, 23, 'DF', 'Olga', 'Carmona', 'Spanish', 'ESP'),
    ('ESP20', 20, 26, 'DF', 'Rocio', 'Galvez', 'Spanish', 'ESP'),
    ('ESP21', 21, 32, 'MF', 'Claudia', 'Zornoza', 'Spanish', 'ESP'),
    ('ESP22', 22, 22, 'FW', 'Athenea', 'del Castillo', 'Spanish', 'ESP'),
    ('ESP23', 23, 22, 'GK', 'Cata', 'Coll', 'Spanish', 'ESP');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('ZAM01', 1, 25, 'GK', 'Catherine', 'Musonda', 'Zambian', 'ZAM'),
    ('ZAM02', 2, 19, 'DF', 'Judith', 'Soko', 'Zambian', 'ZAM'),
    ('ZAM03', 3, 22, 'DF', 'Lushomo', 'Mweemba', 'Zambian', 'ZAM'),
    ('ZAM04', 4, 33, 'MF', 'Susan', 'Banda', 'Zambian', 'ZAM'),
    ('ZAM05', 5, 25, 'DF', 'Mary', 'Mulenga', 'Zambian', 'ZAM'),
    ('ZAM06', 6, 25, 'MF', 'Mary', 'Wilombe', 'Zambian', 'ZAM'),
    ('ZAM07', 7, 22, 'FW', 'Ochumba', 'Lubandji', 'Zambian', 'ZAM'),
    ('ZAM08', 8, 26, 'DF', 'Margaret', 'Belemu', 'Zambian', 'ZAM'),
    ('ZAM09', 9, 28, 'MF', 'Hellen', 'Mubanga', 'Zambian', 'ZAM'),
    ('ZAM10', 10, 18, 'MF', 'Comfort', 'Selemani', 'Zambian', 'ZAM'),
    ('ZAM11', 11, 23, 'FW', 'Barbra', 'Banda', 'Zambian', 'ZAM'),
    ('ZAM12', 12, 20, 'MF', 'Evarine', 'Katongo', 'Zambian', 'ZAM'),
    ('ZAM13', 13, 25, 'DF', 'Martha', 'Tembo', 'Zambian', 'ZAM'),
    ('ZAM14', 14, 25, 'MF', 'Ireen', 'Lungu', 'Zambian', 'ZAM'),
    ('ZAM15', 15, 26, 'DF', 'Agness', 'Musase', 'Zambian', 'ZAM'),
    ('ZAM16', 16, 18, 'GK', 'Leticia', 'Lungu', 'Zambian', 'ZAM'),
    ('ZAM17', 17, 23, 'FW', 'Racheal', 'Kundananji', 'Zambian', 'ZAM'),
    ('ZAM18', 18, 21, 'GK', 'Eunice', 'Sakala', 'Zambian', 'ZAM'),
    ('ZAM19', 19, 20, 'FW', 'Siomala', 'Mapepa', 'Zambian', 'ZAM'),
    ('ZAM20', 20, 25, 'MF', 'Hellen', 'Chanda', 'Zambian', 'ZAM'),
    ('ZAM21', 21, 25, 'MF', 'Avell', 'Chitundu', 'Zambian', 'ZAM'),
    ('ZAM22', 22, 18, 'DF', 'Esther', 'Banda', 'Zambian', 'ZAM'),
    ('ZAM23', 23, 27, 'DF', 'Vast', 'Phiri', 'Zambian', 'ZAM');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('CHN01', 1, 25, 'GK', 'Zhu', 'Yu', 'Chinese', 'CHN'),
    ('CHN02', 2, 28, 'DF', 'Li', 'Mengwen', 'Chinese', 'CHN'),
    ('CHN03', 3, 23, 'DF', 'Dou', 'Jiaxing', 'Chinese', 'CHN'),
    ('CHN04', 4, 22, 'DF', 'Wang', 'Linlin', 'Chinese', 'CHN'),
    ('CHN05', 5, 30, 'DF', 'Wu', 'Haiyan', 'Chinese', 'CHN'),
    ('CHN06', 6, 31, 'MF', 'Zhang', 'Xin', 'Chinese', 'CHN'),
    ('CHN07', 7, 28, 'FW', 'Wang', 'Shuang', 'Chinese', 'CHN'),
    ('CHN08', 8, 25, 'MF', 'Yao', 'Wei', 'Chinese', 'CHN'),
    ('CHN09', 9, 21, 'MF', 'Shen', 'Mengyu', 'Chinese', 'CHN'),
    ('CHN10', 10, 34, 'MF', 'Zhang', 'Rui', 'Chinese', 'CHN'),
    ('CHN11', 11, 33, 'FW', 'Wang', 'Shanshan', 'Chinese', 'CHN'),
    ('CHN12', 12, 24, 'GK', 'Xu', 'Huan', 'Chinese', 'CHN'),
    ('CHN13', 13, 29, 'MF', 'Yang', 'Lina', 'Chinese', 'CHN'),
    ('CHN14', 14, 32, 'FW', 'Lou', 'Jiahui', 'Chinese', 'CHN'),
    ('CHN15', 15, 23, 'DF', 'Chen', 'Qiaozhu', 'Chinese', 'CHN'),
    ('CHN16', 16, 27, 'MF', 'Yao', 'Lingwei', 'Chinese', 'CHN'),
    ('CHN17', 17, 27, 'MF', 'Wu', 'Chengshu', 'Chinese', 'CHN'),
    ('CHN18', 18, 28, 'FW', 'Tang', 'Jiali', 'Chinese', 'CHN'),
    ('CHN19', 19, 22, 'MF', 'Zhang', 'Linyan', 'Chinese', 'CHN'),
    ('CHN20', 20, 27, 'FW', 'Xiao', 'Yuyi', 'Chinese', 'CHN'),
    ('CHN21', 21, 32, 'MF', 'Gu', 'Yasha', 'Chinese', 'CHN'),
    ('CHN22', 22, 18, 'GK', 'Pan', 'Hongyan', 'Chinese', 'CHN'),
    ('CHN23', 23, 30, 'DF', 'Gao', 'Chen', 'Chinese', 'CHN');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('DEN01', 1, 23, 'GK', 'Lene', 'Christensen', 'Danish', 'DEN'),
    ('DEN02', 2, 21, 'MF', 'Josefine', 'Hasbo', 'Danish', 'DEN'),
    ('DEN03', 3, 29, 'DF', 'Stine Ballisager', 'Pedersen', 'Danish', 'DEN'),
    ('DEN04', 4, 27, 'DF', 'Rikke', 'Sevecke', 'Danish', 'DEN'),
    ('DEN05', 5, 31, 'DF', 'Simone Boye', 'Sorensen', 'Danish', 'DEN'),
    ('DEN06', 6, 24, 'MF', 'Karen', 'Holmgaard', 'Danish', 'DEN'),
    ('DEN07', 7, 34, 'MF', 'Sanne Troelsgaard', 'Nielsen', 'Danish', 'DEN'),
    ('DEN08', 8, 22, 'MF', 'Emma', 'Snerle', 'Danish', 'DEN'),
    ('DEN09', 9, 26, 'FW', 'Amalie', 'Vangsgaard', 'Danish', 'DEN'),
    ('DEN10', 10, 30, 'FW', 'Pernille', 'Harder', 'Danish', 'DEN'),
    ('DEN11', 11, 32, 'DF', 'Katrine', 'Veje', 'Danish', 'DEN'),
    ('DEN12', 12, 20, 'MF', 'Kathrine Moller', 'Kühl', 'Danish', 'DEN'),
    ('DEN13', 13, 27, 'MF', 'Sara', 'Thige', 'Danish', 'DEN'),
    ('DEN14', 14, 25, 'MF', 'Nicoline', 'Sorensen', 'Danish', 'DEN'),
    ('DEN15', 15, 27, 'DF', 'Frederikke', 'Thogersen', 'Danish', 'DEN'),
    ('DEN16', 16, 30, 'GK', 'Kathrine', 'Larsen', 'Danish', 'DEN'),
    ('DEN17', 17, 25, 'FW', 'Rikke', 'Madsen', 'Danish', 'DEN'),
    ('DEN18', 18, 29, 'DF', 'Luna', 'Gevitz', 'Danish', 'DEN'),
    ('DEN19', 19, 23, 'MF', 'Janni', 'Thomsen', 'Danish', 'DEN'),
    ('DEN20', 20, 25, 'FW', 'Signe', 'Bruun', 'Danish', 'DEN'),
    ('DEN21', 21, 23, 'FW', 'Mille', 'Gejl', 'Danish', 'DEN'),
    ('DEN22', 22, 25, 'GK', 'Maja Bay', 'Ostergaard', 'Danish', 'DEN'),
    ('DEN23', 23, 22, 'DF', 'Sofie', 'Svava', 'Danish', 'DEN');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('ENG01', 1, 30, 'GK', 'Mary', 'Earps', 'British', 'ENG'),
    ('ENG02', 2, 31, 'DF', 'Lucy', 'Bronze', 'British', 'ENG'),
    ('ENG03', 3, 24, 'DF', 'Niamh', 'Charles', 'British', 'ENG'),
    ('ENG04', 4, 26, 'MF', 'Keira', 'Walsh', 'British', 'ENG'),
    ('ENG05', 5, 29, 'DF', 'Alex', 'Greenwood', 'British', 'ENG'),
    ('ENG06', 6, 29, 'DF', 'Millie', 'Bright', 'British', 'ENG'),
    ('ENG07', 7, 21, 'FW', 'Lauren', 'James', 'British', 'ENG'),
    ('ENG08', 8, 24, 'MF', 'Georgia', 'Stanway', 'British', 'ENG'),
    ('ENG09', 9, 31, 'FW', 'Rachel', 'Daly', 'British', 'ENG'),
    ('ENG10', 10, 23, 'MF', 'Ella', 'Toone', 'British', 'ENG'),
    ('ENG11', 11, 22, 'FW', 'Lauren', 'Hemp', 'British', 'ENG'),
    ('ENG12', 12, 30, 'MF', 'Jordan', 'Nobbs', 'British', 'ENG'),
    ('ENG13', 13, 22, 'GK', 'Hannah', 'Hampton', 'British', 'ENG'),
    ('ENG14', 14, 24, 'DF', 'Lotte', 'Wubben-Moy', 'British', 'ENG'),
    ('ENG15', 15, 22, 'DF', 'Esme', 'Morgan', 'British', 'ENG'),
    ('ENG16', 16, 25, 'DF', 'Jess', 'Carter', 'British', 'ENG'),
    ('ENG17', 17, 32, 'MF', 'Laura', 'Coombs', 'British', 'ENG'),
    ('ENG18', 18, 25, 'FW', 'Chloe', 'Kelly', 'British', 'ENG'),
    ('ENG19', 19, 29, 'FW', 'Bethany', 'England', 'British', 'ENG'),
    ('ENG20', 20, 27, 'MF', 'Katie', 'Zelem', 'British', 'ENG'),
    ('ENG21', 21, 23, 'GK', 'Ellie', 'Roebuck', 'British', 'ENG'),
    ('ENG22', 22, 20, 'FW', 'Katie', 'Robinson', 'British', 'ENG'),
    ('ENG23', 23, 24, 'FW', 'Alessia', 'Russo', 'British', 'ENG');


INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('HAI01', 1, 24, 'GK', 'Kerly', 'Theus', 'Haitian', 'HAI'),
    ('HAI02', 2, 26, 'DF', 'Chelsea', 'Surpris', 'Haitian', 'HAI'),
    ('HAI03', 3, 25, 'MF', 'Jennyfer', 'Limage', 'Haitian', 'HAI'),
    ('HAI04', 4, 19, 'DF', 'Tabita', 'Joseph', 'Haitian', 'HAI'),
    ('HAI05', 5, 20, 'MF', 'Maudeline', 'Moryl', 'Haitian', 'HAI'),
    ('HAI06', 6, 19, 'MF', 'Melchie', 'Dumornay', 'Haitian', 'HAI'),
    ('HAI07', 7, 26, 'FW', 'Batcheba', 'Louis', 'Haitian', 'HAI'),
    ('HAI08', 8, 22, 'MF', 'Danielle', 'Etienne', 'Haitian', 'HAI'),
    ('HAI09', 9, 24, 'MF', 'Sherly', 'Jeudy', 'Haitian', 'HAI'),
    ('HAI10', 10, 24, 'FW', 'Nerilia', 'Mondesir', 'Haitian', 'HAI'),
    ('HAI11', 11, 24, 'FW', 'Roseline', 'Eloissaint', 'Haitian', 'HAI'),
    ('HAI12', 12, 19, 'GK', 'Nahomie', 'Ambroise', 'Haitian', 'HAI'),
    ('HAI13', 13, 19, 'DF', 'Betina', 'Petit-Frere', 'Haitian', 'HAI'),
    ('HAI14', 14, 20, 'DF', 'Esthericove', 'Joseph', 'Haitian', 'HAI'),
    ('HAI15', 15, 19, 'FW', 'Darlina', 'Joseph', 'Haitian', 'HAI'),
    ('HAI16', 16, 21, 'DF', 'Milan', 'Pierre-Jerome', 'Haitian', 'HAI'),
    ('HAI17', 17, 25, 'FW', 'Shwendesky', 'Joseph', 'Haitian', 'HAI'),
    ('HAI18', 18, 20, 'MF', 'Noa', 'Ganthier', 'Haitian', 'HAI'),
    ('HAI19', 19, 19, 'MF', 'Dayana', 'Pierre-Louis', 'Haitian', 'HAI'),
    ('HAI20', 20, 26, 'DF', 'Kethna', 'Louis', 'Haitian', 'HAI'),
    ('HAI21', 21, 22, 'DF', 'Ruthny', 'Mathurin', 'Haitian', 'HAI'),
    ('HAI22', 22, 30, 'FW', 'Roselord', 'Borgella', 'Haitian', 'HAI'),
    ('HAI23', 23, 20, 'GK', 'Lara', 'Larco', 'Haitian', 'HAI');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('NED01', 1, 23, 'GK', 'Daphne', 'van Domselaar', 'Dutch', 'NED'),
    ('NED02', 2, 22, 'DF', 'Lynn', 'Wilms', 'Dutch', 'NED'),
    ('NED03', 3, 30, 'DF', 'Stefanie', 'van der Gragt', 'Dutch', 'NED'),
    ('NED04', 4, 24, 'DF', 'Aniek', 'Nouwen', 'Dutch', 'NED'),
    ('NED05', 5, 30, 'DF', 'Merel', 'van Dongen', 'Dutch', 'NED'),
    ('NED06', 6, 26, 'MF', 'Jill', 'Roord', 'Dutch', 'NED'),
    ('NED07', 7, 26, 'FW', 'Lineth', 'Beerensteyn', 'Dutch', 'NED'),
    ('NED08', 8, 33, 'MF', 'Sherida', 'Spitse', 'Dutch', 'NED'),
    ('NED09', 9, 26, 'FW', 'Katja', 'Snoeijs', 'Dutch', 'NED'),
    ('NED10', 10, 31, 'MF', 'Danielle', 'van de Donk', 'Dutch', 'NED'),
    ('NED11', 11, 30, 'FW', 'Lieke', 'Martens', 'Dutch', 'NED'),
    ('NED12', 12, 22, 'MF', 'Jill', 'Baijings', 'Dutch', 'NED'),
    ('NED13', 13, 32, 'FW', 'Renate', 'Jansen', 'Dutch', 'NED'),
    ('NED14', 14, 28, 'MF', 'Jackie', 'Groenen', 'Dutch', 'NED'),
    ('NED15', 15, 24, 'DF', 'Caitlin', 'Dijkstra', 'Dutch', 'NED'),
    ('NED16', 16, 25, 'GK', 'Lize', 'Kop', 'Dutch', 'NED'),
    ('NED17', 17, 24, 'MF', 'Victoria', 'Pelova', 'Dutch', 'NED'),
    ('NED18', 18, 22, 'MF', 'Kerstin', 'Casparij', 'Dutch', 'NED'),
    ('NED19', 19, 17, 'MF', 'Wieke', 'Kaptein', 'Dutch', 'NED'),
    ('NED20', 20, 28, 'DF', 'Dominique', 'Janssen', 'Dutch', 'NED'),
    ('NED21', 21, 23, 'MF', 'Damaris', 'Egurrola', 'Dutch', 'NED'),
    ('NED22', 22, 19, 'FW', 'Esmee', 'Brugts', 'Dutch', 'NED'),
    ('NED23', 23, 25, 'GK', 'Jacintha', 'Weimar', 'Dutch', 'NED');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('POR01', 1, 24, 'GK', 'Ines', 'Pereira', 'Portuguese', 'POR'),
    ('POR02', 2, 23, 'DF', 'Catarina', 'Amado', 'Portuguese', 'POR'),
    ('POR03', 3, 25, 'DF', 'Lucia', 'Alves', 'Portuguese', 'POR'),
    ('POR04', 4, 34, 'DF', 'Silvia', 'Rebelo', 'Portuguese', 'POR'),
    ('POR05', 5, 26, 'DF', 'Joana', 'Marchao', 'Portuguese', 'POR'),
    ('POR06', 6, 21, 'MF', 'Andreia', 'Jacinto', 'Portuguese', 'POR'),
    ('POR07', 7, 25, 'MF', 'Ana', 'Rute', 'Portuguese', 'POR'),
    ('POR08', 8, 26, 'MF', 'Andreia', 'Norton', 'Portuguese', 'POR'),
    ('POR09', 9, 33, 'FW', 'Ana', 'Borges', 'Portuguese', 'POR'),
    ('POR10', 10, 28, 'FW', 'Jessica', 'Silva', 'Portuguese', 'POR'),
    ('POR11', 11, 29, 'MF', 'Tatiana', 'Pinto', 'Portuguese', 'POR'),
    ('POR12', 12, 31, 'GK', 'Patricia', 'Morais', 'Portuguese', 'POR'),
    ('POR13', 13, 27, 'MF', 'Fatima', 'Pinto', 'Portuguese', 'POR'),
    ('POR14', 14, 31, 'MF', 'Dolores', 'Silva', 'Portuguese', 'POR'),
    ('POR15', 15, 33, 'DF', 'Carole', 'Costa', 'Portuguese', 'POR'),
    ('POR16', 16, 28, 'FW', 'Diana', 'Silva', 'Portuguese', 'POR'),
    ('POR17', 17, 22, 'DF', 'Ana', 'Seica', 'Portuguese', 'POR'),
    ('POR18', 18, 35, 'FW', 'Carolina', 'Mendes', 'Portuguese', 'POR'),
    ('POR19', 19, 24, 'DF', 'Diana', 'Gomes', 'Portuguese', 'POR'),
    ('POR20', 20, 20, 'MF', 'Francisca', 'Nazareth', 'Portuguese', 'POR'),
    ('POR21', 21, 25, 'FW', 'Ana', 'Capeta', 'Portuguese', 'POR'),
    ('POR22', 22, 29, 'GK', 'Rute', 'Costa', 'Portuguese', 'POR'),
    ('POR23', 23, 21, 'FW', 'Telma', 'Encarnacao', 'Portuguese', 'POR');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('USA01', 1, 35, 'GK', 'Alyssa', 'Naeher', 'American', 'USA'),
    ('USA02', 2, 24, 'MF', 'Ashley', 'Sanchez', 'American', 'USA'),
    ('USA03', 3, 30, 'DF', 'Sofia', 'Huerta', 'American', 'USA'),
    ('USA04', 4, 23, 'DF', 'Naomi', 'Girma', 'American', 'USA'),
    ('USA05', 5, 34, 'DF', 'Kelley', 'O''Hara', 'American', 'USA'),
    ('USA06', 6, 30, 'FW', 'Lynn', 'Williams', 'American', 'USA'),
    ('USA07', 7, 18, 'FW', 'Alyssa', 'Thompson', 'American', 'USA'),
    ('USA08', 8, 31, 'MF', 'Julie', 'Ertz', 'American', 'USA'),
    ('USA09', 9, 25, 'MF', 'Savannah', 'DeMelo', 'American', 'USA'),
    ('USA10', 10, 29, 'MF', 'Lindsey', 'Horan', 'American', 'USA'),
    ('USA11', 11, 22, 'FW', 'Sophia', 'Smith', 'American', 'USA'),
    ('USA12', 12, 26, 'DF', 'Alana', 'Cook', 'American', 'USA'),
    ('USA13', 13, 34, 'FW', 'Alex', 'Morgan', 'American', 'USA'),
    ('USA14', 14, 29, 'DF', 'Emily', 'Sonnett', 'American', 'USA'),
    ('USA15', 15, 38, 'FW', 'Megan', 'Rapinoe', 'American', 'USA'),
    ('USA16', 16, 28, 'MF', 'Rose', 'Lavelle', 'American', 'USA'),
    ('USA17', 17, 27, 'MF', 'Andi', 'Sullivan', 'American', 'USA'),
    ('USA18', 18, 27, 'GK', 'Casey', 'Murphy', 'American', 'USA'),
    ('USA19', 19, 31, 'DF', 'Crystal', 'Dunn', 'American', 'USA'),
    ('USA20', 20, 21, 'FW', 'Trinity', 'Rodman', 'American', 'USA'),
    ('USA21', 21, 31, 'GK', 'Aubrey', 'Kingsbury', 'American', 'USA'),
    ('USA22', 22, 32, 'MF', 'Kristie', 'Mewis', 'American', 'USA'),
    ('USA23', 23, 25, 'DF', 'Emily', 'Fox', 'American', 'USA');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('VIE01', 1, 20, 'GK', 'Dao Thi Kieu', 'Oanh', 'Vietnamese', 'VIE'),
    ('VIE02', 2, 23, 'DF', 'Luong Thi Thu', 'Thuong', 'Vietnamese', 'VIE'),
    ('VIE03', 3, 27, 'DF', 'Chuong Thi', 'Kieu', 'Vietnamese', 'VIE'),
    ('VIE04', 4, 32, 'DF', 'Tran Thi', 'Thu', 'Vietnamese', 'VIE'),
    ('VIE05', 5, 28, 'DF', 'Hoang Thi', 'Loan', 'Vietnamese', 'VIE'),
    ('VIE06', 6, 31, 'DF', 'Tran Thi Thuy', 'Nga', 'Vietnamese', 'VIE'),
    ('VIE07', 7, 29, 'MF', 'Nguyen Thi Tuyet', 'Dung', 'Vietnamese', 'VIE'),
    ('VIE08', 8, 34, 'MF', 'Tran Thi Thuy', 'Trang', 'Vietnamese', 'VIE'),
    ('VIE09', 9, 31, 'FW', 'Huynh', 'Nhu', 'Vietnamese', 'VIE'),
    ('VIE10', 10, 22, 'DF', 'Tran Thi Hai', 'Linh', 'Vietnamese', 'VIE'),
    ('VIE11', 11, 28, 'MF', 'Thai Thi', 'Thao', 'Vietnamese', 'VIE'),
    ('VIE12', 12, 28, 'FW', 'Pham Hai', 'Yen', 'Vietnamese', 'VIE'),
    ('VIE13', 13, 29, 'DF', 'Le Thi Diem', 'My', 'Vietnamese', 'VIE'),
    ('VIE14', 14, 29, 'GK', 'Tran Thi Kim', 'Thanh', 'Vietnamese', 'VIE'),
    ('VIE15', 15, 23, 'FW', 'Nguyen Thi Thuy', 'Hang', 'Vietnamese', 'VIE'),
    ('VIE16', 16, 28, 'MF', 'Duong Thi', 'Van', 'Vietnamese', 'VIE'),
    ('VIE17', 17, 30, 'DF', 'Tran Thi Thu', 'Thao', 'Vietnamese', 'VIE'),
    ('VIE18', 18, 19, 'FW', 'Vu Thi', 'Hoa', 'Vietnamese', 'VIE'),
    ('VIE19', 19, 21, 'MF', 'Nguyen Thi Thanh', 'Nha', 'Vietnamese', 'VIE'),
    ('VIE20', 20, 29, 'GK', 'Khong Thi', 'Hang', 'Vietnamese', 'VIE'),
    ('VIE21', 21, 22, 'MF', 'Ngan Thi', 'Van Su', 'Vietnamese', 'VIE'),
    ('VIE22', 22, 28, 'DF', 'Nguyen Thi My', 'Anh', 'Vietnamese', 'VIE'),
    ('VIE23', 23, 29, 'MF', 'Nguyễn Thi Bich', 'Thuy', 'Vietnamese', 'VIE');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('BRA01', 1, 35, 'GK', 'Barbara', ' ', 'Brazilian', 'BRA'),
    ('BRA02', 2, 29, 'DF', 'Antonia', ' ', 'Brazilian', 'BRA'),
    ('BRA03', 3, 27, 'DF', 'Kathellen', ' ', 'Brazilian', 'BRA'),
    ('BRA04', 4, 32, 'DF', 'Rafaelle', 'Souza', 'Brazilian', 'BRA'),
    ('BRA05', 5, 30, 'MF', 'Luana', ' ', 'Brazilian', 'BRA'),
    ('BRA06', 6, 35, 'DF', 'Tamires', ' ', 'Brazilian', 'BRA'),
    ('BRA07', 7, 30, 'FW', 'Andressa', 'Alves', 'Brazilian', 'BRA'),
    ('BRA08', 8, 23, 'MF', 'Ana Vitoria', ' ', 'Brazilian', 'BRA'),
    ('BRA09', 9, 31, 'FW', 'Debinha', ' ', 'Brazilian', 'BRA'),
    ('BRA10', 10, 37, 'FW', 'Marta', ' ', 'Brazilian', 'BRA'),
    ('BRA11', 11, 26, 'MF', 'Adriana', ' ', 'Brazilian', 'BRA'),
    ('BRA12', 12, 28, 'GK', 'Leticia', 'Izidoro', 'Brazilian', 'BRA'),
    ('BRA13', 13, 21, 'DF', 'Bruninha', ' ', 'Brazilian', 'BRA'),
    ('BRA14', 14, 20, 'DF', 'Lauren', ' ', 'Brazilian', 'BRA'),
    ('BRA15', 15, 22, 'MF', 'Duda', 'Sampaio', 'Brazilian', 'BRA'),
    ('BRA16', 16, 29, 'FW', 'Bia', 'Zaneratto', 'Brazilian', 'BRA'),
    ('BRA17', 17, 23, 'MF', 'Ary', 'Borges', 'Brazilian', 'BRA'),
    ('BRA18', 18, 25, 'FW', 'Geyse', ' ', 'Brazilian', 'BRA'),
    ('BRA19', 19, 36, 'DF', 'Monica', ' ', 'Brazilian', 'BRA'),
    ('BRA20', 20, 23, 'MF', 'Angelina', ' ', 'Brazilian', 'BRA'),
    ('BRA21', 21, 23, 'MF', 'Kerolin', ' ', 'Brazilian', 'BRA'),
    ('BRA22', 22, 22, 'GK', 'Camila', ' ', 'Brazilian', 'BRA'),
    ('BRA23', 23, 26, 'FW', 'Gabi', 'Nunes', 'Brazilian', 'BRA');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('FRA01', 1, 28, 'GK', 'Solene', 'Durand', 'French', 'FRA'),
    ('FRA02', 2, 23, 'DF', 'Maelle', 'Lakrar', 'French', 'FRA'),
    ('FRA03', 3, 33, 'DF', 'Wendie', 'Renard', 'French', 'FRA'),
    ('FRA04', 4, 19, 'MF', 'Laurina', 'Fazer', 'French', 'FRA'),
    ('FRA05', 5, 25, 'DF', 'Elisa', 'De Almeida', 'French', 'FRA'),
    ('FRA06', 6, 28, 'MF', 'Sandie', 'Toletti', 'French', 'FRA'),
    ('FRA07', 7, 27, 'DF', 'Sakina', 'Karchaoui', 'French', 'FRA'),
    ('FRA08', 8, 26, 'MF', 'Grace', 'Geyoro', 'French', 'FRA'),
    ('FRA09', 9, 34, 'FW', 'Eugenie', 'Le Sommer', 'French', 'FRA'),
    ('FRA10', 10, 30, 'MF', 'Amel', 'Majri', 'French', 'FRA'),
    ('FRA11', 11, 28, 'FW', 'Kadidiatou', 'Diani', 'French', 'FRA'),
    ('FRA12', 12, 25, 'FW', 'Clara', 'Mateo', 'French', 'FRA'),
    ('FRA13', 13, 22, 'DF', 'Selma', 'Bacha', 'French', 'FRA'),
    ('FRA14', 14, 28, 'DF', 'Aissatou', 'Tounkara', 'French', 'FRA'),
    ('FRA15', 15, 31, 'MF', 'Kenza', 'Dali', 'French', 'FRA'),
    ('FRA16', 16, 31, 'GK', 'Pauline', 'Peyraud-Magnin', 'French', 'FRA'),
    ('FRA17', 17, 30, 'MF', 'Lea', 'Le Garrec', 'French', 'FRA'),
    ('FRA18', 18, 29, 'FW', 'Viviane', 'Asseyi', 'French', 'FRA'),
    ('FRA19', 19, 21, 'FW', 'Naomie', 'Feller', 'French', 'FRA'),
    ('FRA20', 20, 26, 'DF', 'Estelle', 'Cascarino', 'French', 'FRA'),
    ('FRA21', 21, 25, 'GK', 'Constance', 'Picaud', 'French', 'FRA'),
    ('FRA22', 22, 28, 'DF', 'Eve', 'Perisset', 'French', 'FRA'),
    ('FRA23', 23, 19, 'FW', 'Vicki', 'Becho', 'French', 'FRA');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('JAM01', 1, 23, 'GK', 'Sydney', 'Schneider', 'Jamaican', 'JAM'),
    ('JAM02', 2, 17, 'MF', 'Solai', 'Washington', 'Jamaican', 'JAM'),
    ('JAM03', 3, 27, 'DF', 'Vyan', 'Sampson', 'Jamaican', 'JAM'),
    ('JAM04', 4, 24, 'DF', 'Chantelle', 'Swaby', 'Jamaican', 'JAM'),
    ('JAM05', 5, 25, 'DF', 'Konya', 'Plummer', 'Jamaican', 'JAM'),
    ('JAM06', 6, 30, 'MF', 'Havana', 'Solaun', 'Jamaican', 'JAM'),
    ('JAM07', 7, 21, 'MF', 'Peyton', 'McNamara', 'Jamaican', 'JAM'),
    ('JAM08', 8, 30, 'MF', 'Drew', 'Spence', 'Jamaican', 'JAM'),
    ('JAM09', 9, 19, 'FW', 'Kameron', 'Simmonds', 'Jamaican', 'JAM'),
    ('JAM10', 10, 21, 'FW', 'Jody', 'Brown', 'Jamaican', 'JAM'),
    ('JAM11', 11, 26, 'FW', 'Khadija', 'Shaw', 'Jamaican', 'JAM'),
    ('JAM12', 12, 21, 'FW', 'Kiki', 'Van Zanten', 'Jamaican', 'JAM'),
    ('JAM13', 13, 32, 'GK', 'Rebecca', 'Spencer', 'Jamaican', 'JAM'),
    ('JAM14', 14, 26, 'DF', 'Deneisha', 'Blackwood', 'Jamaican', 'JAM'),
    ('JAM15', 15, 31, 'FW', 'Tiffany', 'Cameron', 'Jamaican', 'JAM'),
    ('JAM16', 16, 21, 'FW', 'Paige', 'Bailey-Gayle', 'Jamaican', 'JAM'),
    ('JAM17', 17, 26, 'DF', 'Allyson', 'Swaby', 'Jamaican', 'JAM'),
    ('JAM18', 18, 28, 'MF', 'Trudi', 'Carter', 'Jamaican', 'JAM'),
    ('JAM19', 19, 25, 'DF', 'Tiernny', 'Wiltshire', 'Jamaican', 'JAM'),
    ('JAM20', 20, 26, 'MF', 'Atlanta', 'Primus', 'Jamaican', 'JAM'),
    ('JAM21', 21, 29, 'FW', 'Cheyna', 'Matthews', 'Jamaican', 'JAM'),
    ('JAM22', 22, 26, 'FW', 'Kayla', 'McKenna', 'Jamaican', 'JAM'),
    ('JAM23', 23, 18, 'GK', 'Liya', 'Brooks', 'Jamaican', 'JAM');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('PAN01', 1, 23, 'FW', 'Riley', 'Tanner', 'Panamanian', 'PAN'),
    ('PAN02', 2, 32, 'GK', 'Sasha', 'Fabrega', 'Panamanian', 'PAN'),
    ('PAN03', 3, 22, 'MF', 'Carmen', 'Montenegro', 'Panamanian', 'PAN'),
    ('PAN04', 4, 19, 'MF', 'Emily', 'Cedeno', 'Panamanian', 'PAN'),
    ('PAN05', 5, 34, 'GK', 'Farissa', 'Cordoba', 'Panamanian', 'PAN'),
    ('PAN06', 6, 20, 'DF', 'Rosario', 'Vargas', 'Panamanian', 'PAN'),
    ('PAN07', 7, 21, 'MF', 'Aldrith', 'Quintero', 'Panamanian', 'PAN'),
    ('PAN08', 8, 23, 'DF', 'Nicole', 'De Obaldia', 'Panamanian', 'PAN'),
    ('PAN09', 9, 20, 'DF', 'Wendy', 'Natis', 'Panamanian', 'PAN'),
    ('PAN10', 10, 31, 'DF', 'Rebeca', 'Espinosa', 'Panamanian', 'PAN'),
    ('PAN11', 11, 25, 'FW', 'Karla', 'Riley', 'Panamanian', 'PAN'),
    ('PAN12', 12, 27, 'MF', 'Laurie', 'Batista', 'Panamanian', 'PAN'),
    ('PAN13', 13, 24, 'MF', 'Erika', 'Hernandez', 'Panamanian', 'PAN'),
    ('PAN14', 14, 28, 'MF', 'Schiandra', 'Gonzalez', 'Panamanian', 'PAN'),
    ('PAN15', 15, 26, 'DF', 'Carina', 'Baltrip-Reyes', 'Panamanian', 'PAN'),
    ('PAN16', 16, 30, 'MF', 'Natalia', 'Mills', 'Panamanian', 'PAN'),
    ('PAN17', 17, 22, 'GK', 'Yenith', 'Bailey', 'Panamanian', 'PAN'),
    ('PAN18', 18, 22, 'FW', 'Lineth', 'Cedeno', 'Panamanian', 'PAN'),
    ('PAN19', 19, 20, 'DF', 'Hilary', 'Jaen', 'Panamanian', 'PAN'),
    ('PAN20', 20, 27, 'DF', 'Katherine', 'Castillo', 'Panamanian', 'PAN'),
    ('PAN21', 21, 19, 'MF', 'Deysire', 'Salazar', 'Panamanian', 'PAN'),
    ('PAN22', 22, 26, 'DF', 'Yomira', 'Pinzn', 'Panamanian', 'PAN'),
    ('PAN23', 23, 26, 'MF', 'Marta', 'Cox', 'Panamanian', 'PAN');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('ARG01', 1, 39, 'GK', 'Vanina', 'Correa', 'Argentinian', 'ARG'),
    ('ARG02', 2, 29, 'DF', 'Adriana', 'Sachs', 'Argentinian', 'ARG'),
    ('ARG03', 3, 29, 'DF', 'Eliana', 'Stabile', 'Argentinian', 'ARG'),
    ('ARG04', 4, 27, 'DF', 'Julieta', 'Cruz', 'Argentinian', 'ARG'),
    ('ARG05', 5, 32, 'MF', 'Vanesa', 'Santana', 'Argentinian', 'ARG'),
    ('ARG06', 6, 27, 'DF', 'Aldana', 'Cometti', 'Argentinian', 'ARG'),
    ('ARG07', 7, 29, 'MF', 'Romina', 'Nunez', 'Argentinian', 'ARG'),
    ('ARG08', 8, 22, 'MF', 'Daiana', 'Falfan', 'Argentinian', 'ARG'),
    ('ARG09', 9, 20, 'FW', 'Paulina', 'Gramaglia', 'Argentinian', 'ARG'),
    ('ARG10', 10, 21, 'MF', 'Dalila', 'Ippolito', 'Argentinian', 'ARG'),
    ('ARG11', 11, 25, 'FW', 'Yamila', 'Rodriguez', 'Argentinian', 'ARG'),
    ('ARG12', 12, 17, 'GK', 'Lara', 'Esponda', 'Argentinian', 'ARG'),
    ('ARG13', 13, 23, 'DF', 'Sophia', 'Braun', 'Argentinian', 'ARG'),
    ('ARG14', 14, 33, 'DF', 'Miriam', 'Mayorga', 'Argentinian', 'ARG'),
    ('ARG15', 15, 30, 'FW', 'Florencia', 'Bonsegundo', 'Argentinian', 'ARG'),
    ('ARG16', 16, 24, 'MF', 'Lorena', 'Benitez', 'Argentinian', 'ARG'),
    ('ARG17', 17, 28, 'MF', 'Camila', 'Gomez Ares', 'Argentinian', 'ARG'),
    ('ARG18', 18, 34, 'DF', 'Gabriela', 'Chavez', 'Argentinian', 'ARG'),
    ('ARG19', 19, 30, 'FW', 'Mariana', 'Larroquette', 'Argentinian', 'ARG'),
    ('ARG20', 20, 19, 'DF', 'Chiara', 'Singarella', 'Argentinian', 'ARG'),
    ('ARG21', 21, 29, 'FW', 'Erica', 'Lonigro', 'Argentinian', 'ARG'),
    ('ARG22', 22, 33, 'FW', 'Estefania', 'Banini', 'Argentinian', 'ARG'),
    ('ARG23', 23, 26, 'GK', 'Abigail', 'Chaves', 'Argentinian', 'ARG');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('ITA01', 1, 30, 'GK', 'Laura', 'Giuliani', 'Italian', 'ITA'),
    ('ITA02', 2, 20, 'MF', 'Emma', 'Severini', 'Italian', 'ITA'),
    ('ITA03', 3, 23, 'DF', 'Benedetta', 'Orsi', 'Italian', 'ITA'),
    ('ITA04', 4, 26, 'DF', 'Lucia', 'Di Guglielmo', 'Italian', 'ITA'),
    ('ITA05', 5, 29, 'DF', 'Elena', 'Linari', 'Italian', 'ITA'),
    ('ITA06', 6, 25, 'MF', 'Manuela', 'Giugliano', 'Italian', 'ITA'),
    ('ITA07', 7, 23, 'FW', 'Sofia', 'Cantore', 'Italian', 'ITA'),
    ('ITA08', 8, 32, 'FW', 'Barbara', 'Bonansea', 'Italian', 'ITA'),
    ('ITA09', 9, 29, 'FW', 'Valentina', 'Giacinti', 'Italian', 'ITA'),
    ('ITA10', 10, 33, 'FW', 'Cristiana', 'Girelli', 'Italian', 'ITA'),
    ('ITA11', 11, 23, 'FW', 'Benedetta', 'Glionna', 'Italian', 'ITA'),
    ('ITA12', 12, 28, 'GK', 'Rachele', 'Baldi', 'Italian', 'ITA'),
    ('ITA13', 13, 32, 'DF', 'Elisa', 'Bartoli', 'Italian', 'ITA'),
    ('ITA14', 14, 18, 'FW', 'Chiara', 'Beccari', 'Italian', 'ITA'),
    ('ITA15', 15, 25, 'FW', 'Annamaria', 'Serturini', 'Italian', 'ITA'),
    ('ITA16', 16, 16, 'MF', 'Giulia', 'Dragoni', 'Italian', 'ITA'),
    ('ITA17', 17, 26, 'DF', 'Lisa', 'Boattin', 'Italian', 'ITA'),
    ('ITA18', 18, 23, 'MF', 'Arianna', 'Caruso', 'Italian', 'ITA'),
    ('ITA19', 19, 24, 'DF', 'Martina', 'Lenzini', 'Italian', 'ITA'),
    ('ITA20', 20, 23, 'MF', 'Giada', 'Greggi', 'Italian', 'ITA'),
    ('ITA21', 21, 32, 'MF', 'Valentina', 'Cernoia', 'Italian', 'ITA'),
    ('ITA22', 22, 26, 'GK', 'Francesca', 'Durante', 'Italian', 'ITA'),
    ('ITA23', 23, 29, 'DF', 'Cecilia', 'Salvai', 'Italian', 'ITA');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('SAF01', 1, 28, 'GK', 'Kaylin', 'Swart', 'South African', 'SAF'),
    ('SAF02', 2, 31, 'DF', 'Lebogang', 'Ramalepe', 'South African', 'SAF'),
    ('SAF03', 3, 24, 'DF', 'Bongeka', 'Gamede', 'South African', 'SAF'),
    ('SAF04', 4, 37, 'DF', 'Noko', 'Matlou', 'South African', 'SAF'),
    ('SAF05', 5, 21, 'DF', 'Fikile', 'Magama', 'South African', 'SAF'),
    ('SAF06', 6, 22, 'FW', 'Noxolo', 'Cesane', 'South African', 'SAF'),
    ('SAF07', 7, 21, 'DF', 'Karabo', 'Dhlamini', 'South African', 'SAF'),
    ('SAF08', 8, 28, 'FW', 'Hildah', 'Magaia', 'South African', 'SAF'),
    ('SAF09', 9, 25, 'FW', 'Gabriela', 'Salgado', 'South African', 'SAF'),
    ('SAF10', 10, 25, 'MF', 'Linda', 'Motlhalo', 'South African', 'SAF'),
    ('SAF11', 11, 27, 'FW', 'Thembi', 'Kgatlana', 'South African', 'SAF'),
    ('SAF12', 12, 29, 'FW', 'Jermaine', 'Seoposenwe', 'South African', 'SAF'),
    ('SAF13', 13, 33, 'DF', 'Bambanani', 'Mbane', 'South African', 'SAF'),
    ('SAF14', 14, 26, 'DF', 'Tiisetso', 'Makhubela', 'South African', 'SAF'),
    ('SAF15', 15, 30, 'MF', 'Refiloe', 'Jane', 'South African', 'SAF'),
    ('SAF16', 16, 30, 'GK', 'Andile', 'Dlamini', 'South African', 'SAF'),
    ('SAF17', 17, 30, 'FW', 'Melinda', 'Kgadiete', 'South African', 'SAF'),
    ('SAF18', 18, 22, 'MF', 'Sibulele', 'Holweni', 'South African', 'SAF'),
    ('SAF19', 19, 28, 'MF', 'Kholosa', 'Biyan', 'South African', 'SAF'),
    ('SAF20', 20, 29, 'MF', 'Robyn', 'Moodaly', 'South African', 'SAF'),
    ('SAF21', 21, 28, 'GK', 'Kebotseng', 'Moletsane', 'South African', 'SAF'),
    ('SAF22', 22, 27, 'MF', 'Nomvula', 'Kgoale', 'South African', 'SAF'),
    ('SAF23', 23, 20, 'FW', 'Wendy', 'Shongwe', 'South African', 'SAF');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('SWE01', 1, 27, 'GK', 'Zecira', 'Musovic', 'Swedish', 'SWE'),
    ('SWE02', 2, 30, 'DF', 'Jonna', 'Andersson', 'Swedish', 'SWE'),
    ('SWE03', 3, 36, 'DF', 'Linda', 'Sembrant', 'Swedish', 'SWE'),
    ('SWE04', 4, 26, 'DF', 'Stina', 'Lennartsson', 'Swedish', 'SWE'),
    ('SWE05', 5, 20, 'DF', 'Anna', 'Sandberg', 'Swedish', 'SWE'),
    ('SWE06', 6, 29, 'DF', 'Magdalena', 'Eriksson', 'Swedish', 'SWE'),
    ('SWE07', 7, 27, 'FW', 'Madelen', 'Janogy', 'Swedish', 'SWE'),
    ('SWE08', 8, 27, 'FW', 'Lina', 'Hurtig', 'Swedish', 'SWE'),
    ('SWE09', 9, 33, 'MF', 'Kosovare', 'Asllani', 'Swedish', 'SWE'),
    ('SWE10', 10, 33, 'FW', 'Sofia', 'Jakobsson', 'Swedish', 'SWE'),
    ('SWE11', 11, 27, 'FW', 'Stina', 'Blackstenius', 'Swedish', 'SWE'),
    ('SWE12', 12, 30, 'GK', 'Jennifer', 'Falk', 'Swedish', 'SWE'),
    ('SWE13', 13, 30, 'DF', 'Amanda', 'Ilestedt', 'Swedish', 'SWE'),
    ('SWE14', 14, 26, 'DF', 'Nathalie', 'Bjorn', 'Swedish', 'SWE'),
    ('SWE15', 15, 25, 'FW', 'Rebecka', 'Blomqvist', 'Swedish', 'SWE'),
    ('SWE16', 16, 26, 'MF', 'Filippa', 'Angeldahl', 'Swedish', 'SWE'),
    ('SWE17', 17, 38, 'MF', 'Caroline', 'Seger', 'Swedish', 'SWE'),
    ('SWE18', 18, 29, 'FW', 'Fridolina', 'Rolf', 'Swedish', 'SWE'),
    ('SWE19', 19, 26, 'MF', 'Johanna', 'Rytting Kaneryd', 'Swedish', 'SWE'),
    ('SWE20', 20, 20, 'MF', 'Hanna', 'Bennison', 'Swedish', 'ENG'),
    ('SWE21', 21, 28, 'GK', 'Tove', 'Enblom', 'Swedish', 'SWE'),
    ('SWE22', 22, 32, 'MF', 'Olivia', 'Schough', 'Swedish', 'SWE'),
    ('SWE23', 23, 30, 'MF', 'Elin', 'Rubensson', 'Swedish', 'SWE');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('COL01', 1, 28, 'GK', 'Catalina', 'Perez', 'Colombian', 'COL'),
    ('COL02', 2, 22, 'DF', 'Manuela', 'Vanegas', 'Colombian', 'COL'),
    ('COL03', 3, 28, 'DF', 'Daniela', 'Arias', 'Colombian', 'COL'),
    ('COL04', 4, 34, 'MF', 'Diana', 'Ospina', 'Colombian', 'COL'),
    ('COL05', 5, 25, 'MF', 'Lorena', 'Bedoya', 'Colombian', 'COL'),
    ('COL06', 6, 32, 'MF', 'Daniela', 'Montoya', 'Colombian', 'COL'),
    ('COL07', 7, 21, 'MF', 'Maria Camila', 'Reyes', 'Colombian', 'COL'),
    ('COL08', 8, 27, 'MF', 'Marcela', 'Restrepo', 'Colombian', 'COL'),
    ('COL09', 9, 24, 'MF', 'Mayra', 'Ramirez', 'Colombian', 'COL'),
    ('COL10', 10, 27, 'MF', 'Leicy', 'Santos', 'Colombian', 'COL'),
    ('COL11', 11, 33, 'FW', 'Catalina', 'Usme', 'Colombian', 'COL'),
    ('COL12', 12, 35, 'GK', 'Sandra', 'Sepulveda', 'Colombian', 'COL'),
    ('COL13', 13, 20, 'GK', 'Natalia', 'Giraldo', 'Colombian', 'COL'),
    ('COL14', 14, 19, 'DF', 'Angela', 'Baron', 'Colombian', 'COL'),
    ('COL15', 15, 18, 'DF', 'Ana Maria', 'Guzman', 'Colombian', 'COL'),
    ('COL16', 16, 31, 'MF', 'Lady', 'Andrade', 'Colombian', 'COL'),
    ('COL17', 17, 32, 'DF', 'Carolina', 'Arias', 'Colombian', 'COL'),
    ('COL18', 18, 18, 'FW', 'Linda', 'Caicedo', 'Colombian', 'COL'),
    ('COL19', 19, 26, 'DF', 'Jorelyn', 'Carabali', 'Colombian', 'COL'),
    ('COL20', 20, 24, 'DF', 'Monica', 'Ramos', 'Colombian', 'COL'),
    ('COL21', 21, 25, 'FW', 'Ivonne', 'Chacon', 'Colombian', 'COL'),
    ('COL22', 22, 26, 'DF', 'Daniela', 'Caracas', 'Colombian', 'COL'),
    ('COL23', 23, 25, 'FW', 'Elexa', 'Bahr', 'Colombian', 'COL');


INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('GER01', 1, 28, 'GK', 'Merle', 'Frohms', 'German', 'GER'),
    ('GER02', 2, 25, 'MF', 'Chantal', 'Hagel', 'German', 'GER'),
    ('GER03', 3, 31, 'DF', 'Kathrin', 'Hendrich', 'German', 'GER'),
    ('GER04', 4, 23, 'DF', 'Sophia', 'Kleinherne', 'German', 'GER'),
    ('GER05', 5, 33, 'DF', 'Marina', 'Hegering', 'German', 'GER'),
    ('GER06', 6, 21, 'MF', 'Lena', 'Oberdorf', 'German', 'GER'),
    ('GER07', 7, 25, 'FW', 'Lea', 'Schuller', 'German', 'GER'),
    ('GER08', 8, 23, 'MF', 'Sydney', 'Lohmann', 'German', 'GER'),
    ('GER09', 9, 32, 'FW', 'Svenja', 'Huth', 'German', 'GER'),
    ('GER10', 10, 25, 'FW', 'Laura', 'Freigang', 'German', 'GER'),
    ('GER11', 11, 32, 'FW', 'Alexandra', 'Popp', 'German', 'GER'),
    ('GER12', 12, 32, 'GK', 'Ann-Katrin', 'Berger', 'German', 'GER'),
    ('GER13', 13, 28, 'MF', 'Sara', 'Däbritz', 'German', 'GER'),
    ('GER14', 14, 23, 'MF', 'Lena', 'Lattwein', 'German', 'GER'),
    ('GER15', 15, 22, 'DF', 'Sjoeke', 'Nüsken', 'German', 'GER'),
    ('GER16', 16, 23, 'FW', 'Nicole', 'Anyomi', 'German', 'GER'),
    ('GER17', 17, 27, 'DF', 'Felicitas', 'Rauch', 'German', 'GER'),
    ('GER18', 18, 29, 'MF', 'Melanie', 'Leupolz', 'German', 'GER'),
    ('GER19', 19, 22, 'FW', 'Klara', 'Buhl', 'German', 'GER'),
    ('GER20', 20, 28, 'MF', 'Lina', 'Magull', 'German', 'GER'),
    ('GER21', 21, 23, 'GK', 'Stina', 'Johannes', 'German', 'GER'),
    ('GER22', 22, 20, 'MF', 'Jule', 'Brand', 'German', 'GER'),
    ('GER23', 23, 31, 'DF', 'Sara', 'Doorsoun', 'German', 'GER');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('MOR01', 1, 33, 'GK', 'Khadija', 'Er-Rmichi', 'Moroccan', 'MOR'),
    ('MOR02', 2, 23, 'DF', 'Zineb', 'Redouani', 'Moroccan', 'MOR'),
    ('MOR03', 3, 25, 'DF', 'Nouhaila', 'Benzina', 'Moroccan', 'MOR'),
    ('MOR04', 4, 19, 'MF', 'Sarah', 'Kassi', 'Moroccan', 'MOR'),
    ('MOR05', 5, 20, 'DF', 'Nesryne', 'El Chad', 'Moroccan', 'MOR'),
    ('MOR06', 6, 28, 'MF', 'Elodie', 'Nakkach', 'Moroccan', 'MOR'),
    ('MOR07', 7, 32, 'FW', 'Ghizlane', 'Chebbak', 'Moroccan', 'MOR'),
    ('MOR08', 8, 33, 'MF', 'Salma', 'Amani', 'Moroccan', 'MOR'),
    ('MOR09', 9, 30, 'FW', 'Ibtissam', 'Jraidi', 'Moroccan', 'MOR'),
    ('MOR10', 10, 35, 'MF', 'Najat', 'Badri', 'Moroccan', 'MOR'),
    ('MOR11', 11, 24, 'MF', 'Fatima', 'Tagnaout', 'Moroccan', 'MOR'),
    ('MOR12', 12, 32, 'GK', 'Assia', 'Zouhair', 'Moroccan', 'MOR'),
    ('MOR13', 13, 22, 'DF', 'Sabah', 'Seghir', 'Moroccan', 'MOR'),
    ('MOR14', 14, 21, 'DF', 'Rkia', 'Mazrouai', 'Moroccan', 'MOR'),
    ('MOR15', 15, 22, 'FW', 'Fatima Zohra', 'Gharbi', 'Moroccan', 'MOR'),
    ('MOR16', 16, 26, 'MF', 'Anissa', 'Lahmari', 'Moroccan', 'MOR'),
    ('MOR17', 17, 28, 'DF', 'Hanane', 'Ait El Haj', 'Moroccan', 'MOR'),
    ('MOR18', 18, 20, 'FW', 'Kenza', 'Chapelle', 'Moroccan', 'MOR'),
    ('MOR19', 19, 21, 'FW', 'Sakina', 'Ouzraoui Diki', 'Moroccan', 'MOR'),
    ('MOR20', 20, 21, 'FW', 'Sofia', 'Bouftini', 'Moroccan', 'MOR'),
    ('MOR21', 21, 23, 'DF', 'Yasmin', 'Mrabet', 'Moroccan', 'MOR'),
    ('MOR22', 22, 22, 'GK', 'Ines', 'Arouaissa', 'Moroccan', 'MOR'),
    ('MOR23', 23, 27, 'FW', 'Rosella', 'Ayane', 'Moroccan', 'MOR');

INSERT INTO Player (playerID, pnumber, age, position, firstName, lastName, nationality, teamID)
VALUES
    ('KOR01', 1, 35, 'GK', 'Yoon', 'Young-geul', 'Korean', 'KOR'),
    ('KOR02', 2, 22, 'DF', 'Choo', 'Hyo-joo', 'Korean', 'KOR'),
    ('KOR03', 3, 26, 'DF', 'Hong', 'Hye-ji', 'Korean', 'KOR'),
    ('KOR04', 4, 34, 'DF', 'Shim', 'Seo-yeon', 'Korean', 'KOR'),
    ('KOR05', 5, 34, 'MF', 'Kim', 'Yun-ji', 'Korean', 'KOR'),
    ('KOR06', 6, 32, 'DF', 'Lim', 'Seon-joo', 'Korean', 'KOR'),
    ('KOR07', 7, 26, 'FW', 'Son', 'Hwa-yeon', 'Korean', 'KOR'),
    ('KOR08', 8, 35, 'MF', 'Cho', 'So-hyun', 'Korean', 'KOR'),
    ('KOR09', 9, 29, 'MF', 'Lee', 'Geum-min', 'Korean', 'KOR'),
    ('KOR10', 10, 32, 'MF', 'Ji', 'So-yun', 'Korean', 'KOR'),
    ('KOR11', 11, 28, 'FW', 'Choe', 'Yu-ri', 'Korean', 'KOR'),
    ('KOR12', 12, 31, 'FW', 'Moon', 'Mi-ra', 'Korean', 'KOR'),
    ('KOR13', 13, 36, 'FW', 'Park', 'Eun-sun', 'Korean', 'KOR'),
    ('KOR14', 14, 30, 'MF', 'Jeon', 'Eun-ha', 'Korean', 'KOR'),
    ('KOR15', 15, 20, 'MF', 'Chun', 'Ga-ram', 'Korean', 'KOR'),
    ('KOR16', 16, 29, 'DF', 'Jang', 'Sel-gi', 'Korean', 'KOR'),
    ('KOR17', 17, 31, 'DF', 'Lee', 'Young-ju', 'Korean', 'KOR'),
    ('KOR18', 18, 38, 'GK', 'Kim', 'Jung-mi', 'Korean', 'KOR'),
    ('KOR19', 19, 16, 'FW', 'Casey', 'Phair', 'Korean', 'KOR'),
    ('KOR20', 20, 33, 'DF', 'Kim', 'Hye-ri', 'Korean', 'KOR'),
    ('KOR21', 21, 25, 'GK', 'Ryu', 'Ji-soo', 'Korean', 'KOR'),
    ('KOR22', 22, 18, 'MF', 'Bae', 'Ye-bin', 'Korean', 'KOR'),
    ('KOR23', 23, 25, 'FW', 'Kang', 'Chae-rim', 'Korean', 'KOR');

